<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:j4lif="http://java4less.com/fop/iform"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:j4lext="xalan://com.java4less.xreport.fop.XLSTExtension"
                extension-element-prefixes="j4lext j4luserext"
                xmlns:j4luserext="xalan://com.java4less.xreport.fop.XLSTDummyExtension">
    <xsl:import href="ADMI-PDF-UTILS.xsl"/>
    <lic xmlns="com.java4less.xreport.fop.lic">
        <data>
            PGNvbXBhbnk+PG5hbWU+TUFUVEhFVyAgQ0FCUkVSQTwvbmFtZT48ZGF0ZT4wMS0wNS0yMDIwPC9kYXRlPjxudW1iZXI+OTc4NTwvbnVtYmVyPjx0eXBlPnJlZ3VsYXI8L3R5cGU+PC9jb21wYW55Pg==
        </data>
        <hash>x+XkPB8R3rJyGWjA05nWSeEml1g=</hash>
    </lic>
    <xsl:template match="/">
        <xsl:comment>Generated by J4L FO Designer 2.13.*</xsl:comment>
        <xsl:comment>Apex Encoding: false</xsl:comment>
        <xsl:comment>Target environment: cloud</xsl:comment>
        <fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:fox="http://xmlgraphics.apache.org/fop/extensions">
            <fo:layout-master-set>
                <xsl:comment>ID Master1 43233148-d12a-4a45-ad14-654f7501d9b4</xsl:comment>
                <fo:simple-page-master master-name="master0" page-height="21.6cm" page-width="27.9cm"
                                       margin-top="0.635cm" margin-bottom="0.635cm" margin-left="0.635cm"
                                       margin-right="0.635cm">
                    <fo:region-body region-name="body0" margin-top="3.52cm" margin-bottom="0.32cm"/>
                    <fo:region-before region-name="header0" extent="3.52cm"/>
                    <fo:region-after region-name="footer0" extent="0.32cm"/>
                </fo:simple-page-master>
            </fo:layout-master-set>
            <fo:page-sequence master-reference="master0">
                <fo:static-content flow-name="header0">
                    <xsl:comment>ID Page Header e6a58c10-f75b-4538-9544-c52c85062a9a</xsl:comment>
                    <fo:table table-layout="fixed" width="26.63cm">
                        <fo:table-column column-width="5.12cm"/>
                        <fo:table-column column-width="21.51cm"/>
                        <fo:table-body>
                            <xsl:comment>repetition of Page Header</xsl:comment>
                            <fo:table-row height="3.52cm">
                                <fo:table-cell number-columns-spanned="1">
                                    <xsl:comment>ID New f80e06d8-f73e-4e6e-bc4b-13fd6f3e8ed9</xsl:comment>
                                    <fo:block font-size="10pt" font-family="SansSerif" color="#000000" text-align="left"
                                              margin-left="0.0cm" margin-right="0.24cm" margin-top="0.0cm">
                                        <xsl:variable name="imagePath"
                                                      select="concat($GRAPHICS-FOLDER, $LOGO-FILENAME)"/>
                                        <fo:external-graphic content-height="scale-to-fit" scaling="non-uniform">
                                            <xsl:attribute name="src">
                                                <xsl:value-of select="$imagePath"/>
                                            </xsl:attribute>
                                            <xsl:attribute name="height">
                                                <xsl:value-of select="$LOGO-HEIGHT"/>
                                            </xsl:attribute>
                                            <xsl:attribute name="content-width">
                                                <xsl:value-of select="$LOGO-WIDTH"/>
                                            </xsl:attribute>
                                        </fo:external-graphic>
                                    </fo:block>

                                </fo:table-cell>
                                <fo:table-cell number-columns-spanned="1">
                                    <xsl:comment>ID New 79751c7e-3e40-47e1-841c-a9b737e60449</xsl:comment>
                                    <fo:block font-size="12pt" font-family="SansSerif" font-weight="bold"
                                              color="#000000" text-align="center" margin-left="5.12cm"
                                              margin-right="9.99cm" margin-top="1.28cm">LIDP Quality Assurance
                                    </fo:block>
                                    <xsl:comment>ID Copy of New c09b3000-49d2-469e-a0c9-a6980f60b5db</xsl:comment>
                                    <fo:block font-size="12pt" font-family="SansSerif" font-weight="bold"
                                              color="#000000" text-align="center" margin-left="5.12cm"
                                              margin-right="9.99cm" margin-top="0.0cm">Establish Summary Report
                                    </fo:block>

                                </fo:table-cell>
                            </fo:table-row>
                        </fo:table-body>
                    </fo:table>


                </fo:static-content>
                <fo:static-content flow-name="footer0">
                    <xsl:comment>ID Page Footer 1967007b-5924-487e-a854-fa22f6f96489</xsl:comment>
                    <fo:table table-layout="fixed" width="26.63cm">
                        <fo:table-column column-width="26.63cm"/>
                        <fo:table-body>
                            <xsl:comment>repetition of Page Footer</xsl:comment>
                            <fo:table-row height="0.0cm">
                                <fo:table-cell>
                                    <fo:table table-layout="fixed" width="100%">
                                        <fo:table-column column-width="26.63cm"/>
                                        <fo:table-body>
                                            <fo:table-row height="0.0cm">
                                                <fo:table-cell number-columns-spanned="1">
                                                    <fo:block/>
                                                </fo:table-cell>
                                            </fo:table-row>
                                        </fo:table-body>
                                    </fo:table>
                                </fo:table-cell>
                            </fo:table-row>
                        </fo:table-body>
                    </fo:table>

                </fo:static-content>
                <fo:flow flow-name="body0">

                    <xsl:comment>START Area Report Header</xsl:comment>
                    <xsl:if test="XML__ReportExtract">
                        <xsl:for-each select="XML__ReportExtract">
                            <xsl:comment>repetition of Report Header</xsl:comment>
                            <xsl:comment>ID Report Header 0e67cba1-38da-4cff-8b91-039332b96809</xsl:comment>
                            <fo:table table-layout="fixed" width="26.63cm">
                                <fo:table-column column-width="7.36cm"/>
                                <fo:table-column column-width="9.28cm"/>
                                <fo:table-column column-width="3.52cm"/>
                                <fo:table-column column-width="6.47cm"/>
                                <fo:table-body>
                                    <fo:table-row height="3.28cm">
                                        <fo:table-cell number-columns-spanned="1">
                                            <xsl:comment>ID lblCompanyCode 55d14d56-a02f-4e6d-8034-4cc1d1732873
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="3.2cm"
                                                      margin-right="0.36cm" margin-top="0.0cm">Company Code:
                                            </fo:block>
                                            <xsl:comment>ID lblCompanyName 5368e3a1-beea-4631-8d22-d4ec8a23db16
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="3.2cm"
                                                      margin-right="0.36cm" margin-top="0.16cm">Company Name:
                                            </fo:block>
                                            <xsl:comment>ID lblReportDescription 7149d848-7dc7-4f72-b173-f193340d577d
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="3.2cm"
                                                      margin-right="0.36cm" margin-top="0.16cm">Report Description:
                                            </fo:block>
                                            <xsl:comment>ID lblReportID 03d1d15d-9836-4fbd-af70-fff2bcce4bd3
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="3.2cm"
                                                      margin-right="0.36cm" margin-top="0.16cm">Report ID:
                                            </fo:block>
                                            <xsl:comment>ID lblPrintedBy 3da0791a-3f20-4935-8b86-f0781b49ae8c
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="3.2cm"
                                                      margin-right="0.36cm" margin-top="0.16cm">Printed By:
                                            </fo:block>

                                        </fo:table-cell>
                                        <fo:table-cell number-columns-spanned="1">
                                            <xsl:comment>ID fldCompanyCode 80da303a-363e-45a9-9b5b-82169fc22ca3
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="0.28cm"
                                                      margin-top="0.0cm">
                                                <xsl:value-of select="companyCode"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldCompanyName 30e8b900-177d-4415-a20f-86c8938197dd
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="0.28cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of select="companyName"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldReportDescription 96e00316-b919-47a2-b9b6-f04e65a0ff1c
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="0.28cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of select="reportDescription"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldReportID 4cc84b30-c82c-46c2-a72f-77d5fa3ab8f2
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="0.28cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of select="reportID"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldPrintedBy e5631789-74c1-43b3-9cdf-86364bcf5f3b
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="0.28cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of select="printedBy"></xsl:value-of>
                                            </fo:block>

                                        </fo:table-cell>
                                        <fo:table-cell number-columns-spanned="1">
                                            <xsl:comment>ID lblFromDate 7ad02da3-01d3-4cde-82a6-d53f1e0b4a42
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="0.0cm"
                                                      margin-right="0.32cm" margin-top="0.0cm">From Date:
                                            </fo:block>
                                            <xsl:comment>ID lblThruDate 863e2592-ed21-4d23-8ea4-b59905892db0
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="0.0cm"
                                                      margin-right="0.32cm" margin-top="0.16cm">Through Date:
                                            </fo:block>
                                            <xsl:comment>ID lblReportDate 95729359-aff8-4c29-83ce-405b1e958aa2
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="0.0cm"
                                                      margin-right="0.32cm" margin-top="0.16cm">Report Date:
                                            </fo:block>
                                            <xsl:comment>ID lblReportTime c9922612-0a75-4a4b-bf8e-87418fb8fbdc
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" font-weight="bold"
                                                      color="#000000" text-align="left" margin-left="0.0cm"
                                                      margin-right="0.32cm" margin-top="0.16cm">Report Time:
                                            </fo:block>

                                        </fo:table-cell>
                                        <fo:table-cell number-columns-spanned="1">
                                            <xsl:comment>ID fldFromDate 2e44833c-a55b-49f2-a358-2381bc9d123b
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="3.27cm"
                                                      margin-top="0.0cm">
                                                <xsl:value-of
                                                        select="concat(substring(fromDate, 6, 2), '-', substring(fromDate, 9, 2), '-', substring(fromDate, 1, 4))"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldThruDate f834e7fa-2f89-4170-b64e-988256e8403c
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="3.27cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of
                                                        select="concat(substring(thruDate, 6, 2), '-', substring(thruDate, 9, 2), '-', substring(thruDate, 1, 4))"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldReportDate cc98344d-d2ba-4709-b504-ac3806b5e1c0
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="3.27cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of
                                                        select="concat(substring(reportDate, 6, 2), '-', substring(reportDate, 9, 2), '-', substring(reportDate, 1, 4))"></xsl:value-of>
                                            </fo:block>
                                            <xsl:comment>ID fldReportTime f57696e5-241f-4740-b720-bf97469dacf4
                                            </xsl:comment>
                                            <fo:block font-size="10pt" font-family="SansSerif" color="#000000"
                                                      text-align="left" margin-left="0.0cm" margin-right="3.27cm"
                                                      margin-top="0.16cm">
                                                <xsl:value-of select="reportTime"></xsl:value-of>
                                            </fo:block>

                                        </fo:table-cell>
                                    </fo:table-row>
                                    <fo:table-row>
                                        <fo:table-cell number-columns-spanned="4">
                                            <fo:block>
                                                <xsl:comment>START Area Detail area 1</xsl:comment>
                                                <xsl:if test="totals/totalEntrySet/XML__ESTB__TotalEntry">
                                                    <xsl:comment>ID Detail area 1 a83ccc70-159f-4238-9b44-d5fe1afe9409
                                                    </xsl:comment>
                                                    <fo:block font-weight="bold" font-size="11">
                                                        Top 10 Entries with Most Days between Request Date and Last Saved Date
                                                    </fo:block>
                                                    <fo:table table-layout="fixed" width="26.63cm">
                                                        <fo:table-column column-width="1.92cm"/>
                                                        <fo:table-column column-width="2.56cm"/>
                                                        <fo:table-column column-width="2.56cm"/>
                                                        <fo:table-column column-width="2.24cm"/>
                                                        <fo:table-column column-width="2.56cm"/>
                                                        <fo:table-column column-width="1.92cm"/>
                                                        <fo:table-column column-width="2.24cm"/>
                                                        <fo:table-column column-width="1.92cm"/>
                                                        <fo:table-column column-width="2.56cm"/>
                                                        <fo:table-column column-width="2.24cm"/>
                                                        <fo:table-column column-width="2.24cm"/>
                                                        <fo:table-column column-width="1.67cm"/>
                                                        <xsl:comment>ID Detail header 1
                                                            45f42321-bfcb-4de8-a82b-1ae2cb8bcd71
                                                        </xsl:comment>
                                                        <fo:table-header>
                                                            <fo:table-row border-bottom-color="#000000"
                                                                          border-bottom-style="solid"
                                                                          border-bottom-width="thin" height="1.28cm">
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrCompanyCode
                                                                        6ad26eb3-2ba3-45ce-80dc-088fc62d5762
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.2cm" width="1.6cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="left" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Company Code
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrPolicy
                                                                        f56958a0-4667-4f02-9b60-9162662ffc26
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.1733cm"
                                                                                        width="2.1cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="left" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Policy
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrPlan
                                                                        40a22f69-812a-4759-ac9a-f8d0a2568563
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm"
                                                                                        width="2.1cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="left" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Plan
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrIssueDate
                                                                        a9314b09-59f9-4728-96e5-76686f5ddee8
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm"
                                                                                        width="1.76cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Issue Date
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrRequestDate
                                                                        6aeceabe-bf02-4c8d-995a-c311b74e5ef3
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm"
                                                                                        width="1.76cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Request Date
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrRequestTime
                                                                        31536c0a-76dd-4767-b3d9-1347d97ae77c
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm" width="1.28cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Request Time
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrEffectiveDate
                                                                        3c04bfa3-3864-4a2c-b831-61a7e2814bea
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm" width="1.6cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Effective Date
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrEffectiveTime
                                                                        abb71bdf-78d9-4bc9-a588-d091395087c7
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm" width="1.28cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Effective Time
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrLastSavedDate
                                                                        eb482645-1f61-4f55-a1df-790c777fbd0f
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm"
                                                                                        width="1.8933333333333333cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Last Saved Date
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrLastSavedTime
                                                                        af77ff5c-8693-4304-b6aa-aa100bd5342a
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm" width="1.893cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Last Saved Time
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrDaysSinceLastSave
                                                                        1d14b1c5-8354-4084-9f0a-b0a22479bd18
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm" width="1.76cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Days Since Last Save
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrStatusTimingCode
                                                                        1b13a93a-2d8d-4397-8170-029a37c7ca46
                                                                    </xsl:comment>
                                                                    <fo:block-container height="1.173cm" width="1.28cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.0cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Status Timing Code
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                            </fo:table-row>
                                                            <fo:table-row height="0.08cm">
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                            </fo:table-row>
                                                        </fo:table-header>
                                                        <fo:table-body>
                                                            <xsl:for-each
                                                                    select="totals/totalEntrySet/XML__ESTB__TotalEntry">
                                                                <xsl:sort select="daysSinceLastSave" data-type="number"
                                                                          order="descending"/>
                                                                <xsl:if test="position()&lt;=10">
                                                                    <xsl:comment>repetition of Detail area 1
                                                                    </xsl:comment>
                                                                    <fo:table-row height="0.67cm">
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlCompanyCode
                                                                                ea943f6a-7008-4c71-a434-f9a7747aa08d
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="left"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.32cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="companyCode"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlPolicy
                                                                                43b27693-7a8f-42f2-ae33-a5bf30aba0e5
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="left"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.46cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="policy"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlPlan
                                                                                ddf3616c-35e1-4750-9899-10ecee4c6d65
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="left"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.46cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="plan"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlIssueDate
                                                                                474b8534-0fed-403a-9ab1-4fafaf88162c
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.48cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="concat(substring(issueDate, 6, 2), '-', substring(issueDate, 9, 2), '-', substring(issueDate, 1, 4))"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlRequestDate
                                                                                901746ce-64c2-4308-bccd-29f92e6f8ef3
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.8cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="concat(substring(requestDate, 6, 2), '-', substring(requestDate, 9, 2), '-', substring(requestDate, 1, 4))"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlRequestTime
                                                                                9e20e9c8-7e5e-45e4-88fd-1ab8143ced8c
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.64cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="requestTime"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlEffectiveDate
                                                                                9aaf91b1-10c8-4dcd-bf63-d681ce5bc921
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.64cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="concat(substring(effectiveDate, 6, 2), '-', substring(effectiveDate, 9, 2), '-', substring(effectiveDate, 1, 4))"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlEffectiveTime
                                                                                37c8e890-f8d0-45be-a9bb-0644f195292e
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.64cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:choose>
                                                                                    <xsl:when test="effectiveTime&lt;'0'">
                                                                                        00:00:00
                                                                                    </xsl:when>
                                                                                    <xsl:otherwise>
                                                                                        <xsl:value-of select="effectiveTime"></xsl:value-of>
                                                                                    </xsl:otherwise>
                                                                                </xsl:choose>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlLastSavedDate
                                                                                199e82b7-0224-4caa-9a22-61a81b7b2d46
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.67cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:choose>
                                                                                    <xsl:when test="lastSavedDate = ''">
                                                                                        00-00-0000
                                                                                    </xsl:when>
                                                                                    <xsl:otherwise>
                                                                                        <xsl:value-of select="concat(substring(lastSavedDate, 6, 2), '-', substring(lastSavedDate, 9, 2), '-', substring(lastSavedDate, 1, 4))"  ></xsl:value-of>
                                                                                    </xsl:otherwise>
                                                                                </xsl:choose>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlLastSavedTime
                                                                                8f9b3db0-f6bd-4389-bc6b-8e7aeccacb3e
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.35cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:choose>
                                                                                    <xsl:when test="lastSavedTime = ''">
                                                                                        00:00:00
                                                                                    </xsl:when>
                                                                                    <xsl:otherwise>
                                                                                        <xsl:value-of select="lastSavedTime"></xsl:value-of>
                                                                                    </xsl:otherwise>
                                                                                </xsl:choose>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlDurationSinceLastSave
                                                                                2e3587f4-b55a-4e57-9ac7-06e7a4c0d9ef
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.48cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="daysSinceLastSave"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID dtlStatusTimingCode
                                                                                d3089d3a-5ff4-440c-96a7-6eae2ab1e82e
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right="0.39cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="statusTimingCode"></xsl:value-of>
                                                                            </fo:block>

                                                                        </fo:table-cell>
                                                                    </fo:table-row>
                                                                </xsl:if>
                                                            </xsl:for-each>
                                                        </fo:table-body>
                                                    </fo:table>

                                                </xsl:if>

                                                <xsl:comment>END Area Detail area 1</xsl:comment>
                                            </fo:block>
                                        </fo:table-cell>
                                    </fo:table-row>
                                    <fo:table-row>
                                        <fo:table-cell number-columns-spanned="4">
                                            <fo:block>
                                                <xsl:comment>START Area Summary Detail</xsl:comment>
                                                <xsl:if test="totals/totalEntrySet/XML__ESTB__TotalEntry">
                                                    <xsl:comment>ID Summary Detail
                                                        5e39490d-6a87-4f4d-813a-42d2ee1575dc
                                                    </xsl:comment>
                                                    <fo:table table-layout="fixed" width="26.63cm">
                                                        <fo:table-column column-width="3.84cm"/>
                                                        <fo:table-column column-width="3.84cm"/>
                                                        <fo:table-column column-width="3.84cm"/>
                                                        <fo:table-column column-width="15.11cm"/>
                                                        <xsl:comment>ID Summary Header
                                                            307add39-f116-4e7c-ac4f-a9b9de73fd63
                                                        </xsl:comment>
                                                        <fo:table-header>
                                                            <fo:table-row border-bottom-color="#000000"
                                                                          border-bottom-style="solid"
                                                                          border-bottom-width="thin" height="1.28cm">
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrHighestDayCount
                                                                        8d358220-4634-4209-8cb4-305d183c4c2a
                                                                    </xsl:comment>
                                                                    <fo:block-container height=".48cm"
                                                                                        width="3.4cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.64cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Highest Day Count
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrLowestDayCount
                                                                        2cfd0ba4-c68f-40f9-90ca-7707c381bd54
                                                                    </xsl:comment>
                                                                    <fo:block-container height=".48cm"
                                                                                        width="3.4cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.64cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Lowest Day Count
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrAverageDayCount
                                                                        c23d90db-e143-4d5d-8280-bdb31003de0a
                                                                    </xsl:comment>
                                                                    <fo:block-container height=".48cm"
                                                                                        width="3.4cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.64cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Average Day Count
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID hdrNumberOfExtracts
                                                                        792aa1d0-3719-4c90-a263-e0a1fbe7f58a
                                                                    </xsl:comment>
                                                                    <fo:block-container height=".48cm"
                                                                                        width="3.4cm"
                                                                                        margin-left="0.0cm"
                                                                                        margin-top="0.64cm"
                                                                                        display-align="after">
                                                                        <fo:block font-size="10pt"
                                                                                  font-family="SansSerif"
                                                                                  font-weight="bold" color="#000000"
                                                                                  text-align="right" margin-right="0cm"
                                                                                  margin-left="0cm" margin-top="0.0cm">
                                                                            Number of Extracts
                                                                        </fo:block>
                                                                    </fo:block-container>

                                                                </fo:table-cell>
                                                            </fo:table-row>
                                                            <fo:table-row height="0.05cm">
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <fo:block/>
                                                                </fo:table-cell>
                                                            </fo:table-row>
                                                        </fo:table-header>
                                                        <fo:table-body>
                                                            <xsl:comment>repetition of Summary Detail</xsl:comment>
                                                            <fo:table-row height="0.69cm">
                                                                <xsl:for-each
                                                                        select="totals/totalEntrySet/XML__ESTB__TotalEntry">
                                                                    <xsl:sort select="daysSinceLastSave"
                                                                              data-type="number" order="descending"/>
                                                                    <xsl:if test="position()=1">
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID Copy of dtlCompanyCode
                                                                                e3827e93-3ad7-4872-8a90-94e5b413d380
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right=".44cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="daysSinceLastSave"></xsl:value-of>
                                                                            </fo:block>
                                                                        </fo:table-cell>
                                                                    </xsl:if>
                                                                </xsl:for-each>
                                                                <xsl:for-each
                                                                        select="totals/totalEntrySet/XML__ESTB__TotalEntry">
                                                                    <xsl:sort select="daysSinceLastSave"
                                                                              data-type="number" order="descending"/>
                                                                    <xsl:if test="position()=last()">
                                                                        <fo:table-cell number-columns-spanned="1">
                                                                            <xsl:comment>ID Copy of dtlCompanyCode
                                                                                e3827e93-3ad7-4872-8a90-94e5b413d380
                                                                            </xsl:comment>
                                                                            <fo:block font-size="10pt"
                                                                                      font-family="SansSerif"
                                                                                      color="#000000" text-align="right"
                                                                                      margin-left="0.0cm"
                                                                                      margin-right=".44cm"
                                                                                      margin-top="0.32cm">
                                                                                <xsl:value-of
                                                                                        select="daysSinceLastSave"></xsl:value-of>
                                                                            </fo:block>
                                                                        </fo:table-cell>
                                                                    </xsl:if>
                                                                </xsl:for-each>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID Copy of dtlCompanyCode
                                                                        e3827e93-3ad7-4872-8a90-94e5b413d380
                                                                    </xsl:comment>
                                                                    <fo:block font-size="10pt" font-family="SansSerif"
                                                                              color="#000000" text-align="right"
                                                                              margin-left="0.0cm" margin-right=".44cm"
                                                                              margin-top="0.32cm">
                                                                        <xsl:value-of
                                                                                select="round(sum(totals/totalEntrySet/XML__ESTB__TotalEntry/daysSinceLastSave) div count(totals/totalEntrySet/XML__ESTB__TotalEntry/daysSinceLastSave))"></xsl:value-of>
                                                                    </fo:block>
                                                                </fo:table-cell>
                                                                <fo:table-cell number-columns-spanned="1">
                                                                    <xsl:comment>ID Copy of Copy of dtlCompanyCode
                                                                        f94335aa-70f7-449e-9af8-0e74968bbd8b
                                                                    </xsl:comment>
                                                                    <fo:block font-size="10pt" font-family="SansSerif"
                                                                              color="#000000" text-align="right"
                                                                              margin-left="0.0cm" margin-right="11.71cm"
                                                                              margin-top="0.32cm">
                                                                        <xsl:value-of
                                                                                select="count(totals/totalEntrySet/XML__ESTB__TotalEntry/daysSinceLastSave)"></xsl:value-of>
                                                                    </fo:block>
                                                                </fo:table-cell>
                                                            </fo:table-row>
                                                        </fo:table-body>
                                                    </fo:table>
                                                </xsl:if>

                                                <xsl:comment>END Area Summary Detail</xsl:comment>
                                            </fo:block>
                                        </fo:table-cell>
                                    </fo:table-row>
                                    <fo:table-row>
                                        <fo:table-cell number-columns-spanned="4">
                                            <fo:block>

                                                <xsl:comment>START Area Report Footer</xsl:comment>
                                                <xsl:comment>ID Report Footer ad4fdd45-3b4f-401a-b9c7-629d5845594f
                                                </xsl:comment>
                                                <fo:table table-layout="fixed" width="26.63cm">
                                                    <fo:table-column column-width="26.63cm"/>
                                                    <fo:table-body>
                                                        <xsl:comment>repetition of Report Footer</xsl:comment>
                                                        <fo:table-row height="0.0cm">
                                                            <fo:table-cell>
                                                                <fo:table table-layout="fixed" width="100%">
                                                                    <fo:table-column column-width="26.63cm"/>
                                                                    <fo:table-body>
                                                                        <fo:table-row height="0.0cm">
                                                                            <fo:table-cell number-columns-spanned="1">
                                                                                <fo:block/>
                                                                            </fo:table-cell>
                                                                        </fo:table-row>
                                                                    </fo:table-body>
                                                                </fo:table>
                                                            </fo:table-cell>
                                                        </fo:table-row>
                                                    </fo:table-body>
                                                </fo:table>


                                                <xsl:comment>END Area Report Footer</xsl:comment>
                                            </fo:block>
                                        </fo:table-cell>
                                    </fo:table-row>
                                </fo:table-body>
                            </fo:table>
                        </xsl:for-each>

                    </xsl:if>

                    <xsl:comment>END Area Report Header</xsl:comment>
                    <fo:block id="last-page"/>
                </fo:flow>
            </fo:page-sequence>
        </fo:root>
    </xsl:template>
</xsl:stylesheet>
